version: '2'
services:
  # datastore:
  #   image: busybox
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    # volumes_from:
    #   - datastore
  server: &server
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bin/rails server -p 3000 -b 0.0.0.0"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    # volumes_from:
    #   - datastore
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - db
  frontend:
    <<: *server
    command: /bin/sh -c "./bin/webpack-dev-server"
    ports:
      - "3035:3035"

volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
  postgres:
    driver: local